In [2]:
import tensorflow as tf

In [3]:
a = tf.constant(3, tf.float32)
a

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [6]:
type(a.numpy())

numpy.float32

## ANN pvz (minimalus)

In [7]:
x = tf.constant([[4, 5]], tf.float32)

### Visiškai nuo 0

In [15]:
W1 = tf.Variable(tf.random.truncated_normal([3, 2], stddev=0.1, seed=1))
b1 = tf.Variable(tf.random.truncated_normal([1, 2], stddev=0.1, seed=2))
h1 = tf.sigmoid(tf.matmul(W1, tf.transpose(x))+b1)
o = tf.reduce_mean(h1)
o

<tf.Tensor: shape=(), dtype=float32, numpy=0.45175347>

### Naudojant sluoksnių ruošinius

In [ ]:
layer1 = tf.keras.layers.Dense(3, activation=tf.nn.sigmoid)
layer2 = tf.keras.layers.Average()
h1 = layer2(layer1(x))
h1

In [33]:
layer1 = tf.keras.layers.Dense(3, activation=tf.nn.sigmoid)
layer2 = tf.keras.layers.Dense(15, activation=tf.nn.sigmoid)
layer3 = tf.keras.layers.Dense(1, activation=tf.nn.tanh)
#layer2 = tf.keras.layers.Average()
model = tf.keras.Sequential([layer1, layer2, layer3])
model(x)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.63791335]], dtype=float32)>

In [34]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (1, 3)                    9         
                                                                 
 dense_19 (Dense)            (1, 15)                   60        
                                                                 
 dense_20 (Dense)            (1, 1)                    16        
                                                                 
Total params: 85
Trainable params: 85
Non-trainable params: 0
_________________________________________________________________
